version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://recipe:recipe@db:5432/recipe
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=recipe
      - POSTGRES_PASSWORD=recipe
      - POSTGRES_DB=recipe
volumes:
  postgres_data:
